Post http://localhost:3333/events
Content-Type: application/json

{
    "title": 12,
    "details": null,
    "maximumAttendees": 1
}

###

Post http://localhost:3333/events/04b7d94e-bd74-4377-968d-73561e6b8e9f/attendees
Content-Type: application/json

{
    "name": "Diogo Pimenta",
    "email": "teste2@gmail.com"
}

###

Get http://localhost:3333/events/04b7d94e-bd74-4377-968d-73561e6b8e9f


###

Get http://localhost:3333/attendees/3/badge

###

Get http://localhost:3333/attendees/4/check-in

###

Get http://localhost:3333/events/04b7d94e-bd74-4377-968d-73561e6b8e9f/attendees?query=ricardo